version: '3'
networks:
 iiot-net:
   driver: bridge
services:
 
###############################
# docker run --network=iiot-net -p 9042:9042 -p 9160:9160 --name cassandra0 cassandra
 cassandra0:
  image: cassandra
  container_name: cassandra0
  ports:
   - 9042:9042
   - 9160:9160
   - 7199:7199
   - 8778:8778
  networks:
    - iiot-net
#docker run --network=iiot-net -P -p 8080:8080 -e "CASS_HOSTS=cassandra0:9042" -e "REPFACTOR=1" iiot-book/kairosdb
 # kairosdb:
 #  image: iiot-book/kairosdb
 #  container_name: kairosdb
 #  environment:
 #   - CASS_HOSTS=cassandra0:9042
 #   - REPFACTOR=1
 #  ports:
 #   - "4242:4242"
 #   - "8080:8080"
 #  depends_on:
 #   - cassandra0
 #  networks:
 #    - iiot-net
#docker run --network=iiot-net -it -p 1883:1883 -p 9001:9001  --name mqtt0 eclipse-mosquitto
 mqtt:
  image: eclipse-mosquitto
  container_name: mqtt0
  ports:
   - "9001:9001"
   - "1883:1883"
  networks:
    - iiot-net
#docker run --network=iiot-net -p 9092:9092 -p 2181:2181 -e MQTT_URI=tcp://mqtt0:1883 -e KAFKA_ADVERTISED_HOST_NAME=192.168.0.102 venergiac/kafka-mqtt:latest
 kafka:
  image: venergiac/kafka-mqtt:latest
  container_name: kafka0
  environment:
   - KAFKA_ADVERTISED_HOST_NAME=192.168.0.102
   - MQTT_URI=tcp://mqtt0:1883
  ports:
   - "9092:9092"
   - "2181:2181"
  depends_on:
   - mqtt
  networks:
    - iiot-net


